GITHUB_USER_URL = "https://api.github.com/users/{username}"
GITHUB_REPOS_URL = "https://api.github.com/users/{username}/repos?sort=pushed"
GITHUB_EVENTS_URL = "https://api.github.com/users/{username}/events/public"
GITHUB_CONTRIBUTORS_URL = "https://api.github.com/repos/{username}/{repo}/contributors"
GITHUB_COMMITS_URL = "https://api.github.com/repos/{username}/{repo}/commits"
GITHUB_FOLLOWERS_URL = "https://api.github.com/users/{username}/followers"
GITHUB_FOLLOWING_URL = "https://api.github.com/users/{username}/following"
