class Nation:
    nation_mapping = {
        "zh": "China",
        "en": "English-speaking country",
        "ja": "Japan",
        "ko": "Korea",
        "ru": "Russia",
        "de": "Germany",
        "fr": "France",
        "es": "Spanish-speaking country",
        "it": "Italy",
        "pt": "Portuguese-speaking country",
        "ar": "Arabic-speaking country",
        "hi": "India",
        "th": "Thailand",
        "vi": "Vietnam",
        "nl": "Netherlands",
        "sv": "Sweden",
        "no": "Norway",
        "fi": "Finland",
        "da": "Denmark",
        "pl": "Poland",
        "tr": "Turkey",
        "he": "Israel",
        "uk": "Ukraine",
        "el": "Greece",
        "hu": "Hungary",
        "cs": "Czech Republic",
        "ro": "Romania",
        "bg": "Bulgaria",
        "sr": "Serbia",
        "hr": "Croatia",
        "sk": "Slovakia",
        "lt": "Lithuania",
        "lv": "Latvia",
        "et": "Estonia",
        "ms": "Malaysia",
        "id": "Indonesia",
        "tl": "Philippines",
        "fa": "Iran",
        "bn": "Bangladesh",
        "ur": "Pakistan",
        "am": "Ethiopia",
        "sw": "Swahili-speaking country",
        "my": "Myanmar",
        "ne": "Nepal",
        "si": "Sri Lanka",
        "mn": "Mongolia",
        "km": "Cambodia",
        "la": "Laos",
        "ps": "Palestine",
        "af": "Afghanistan",
        "kg": "Kyrgyzstan",
        "uz": "Uzbekistan",
        "tj": "Tajikistan",
        "az": "Azerbaijan",
        "ge": "Georgia",
        "md": "Moldova",
        "bh": "Bahrain",
        "qa": "Qatar",
        "om": "Oman",
        "ye": "Yemen",
        "dz": "Algeria",
        "ma": "Morocco",
        "tn": "Tunisia",
        "sn": "Senegal",
        "gh": "Ghana",
        "ng": "Nigeria",
        "za": "South Africa",
        "ci": "Ivory Coast",
        "cd": "Congo",
        "ao": "Angola",
        "ug": "Uganda",
        "mz": "Mozambique",
        "zm": "Zambia",
        "zw": "Zimbabwe",
        "bw": "Botswana",
        "ke": "Kenya",
        "br": "Brazil",
        "mx": "Mexico",
        "au": "Australia",
        "ca": "Canada",
        "ch": "Switzerland",
        "cl": "Chile",
        "co": "Colombia",
        "cr": "Costa Rica",
        "ec": "Ecuador",
        "eg": "Egypt",
        "gr": "Greece",
        "hk": "Hong Kong",
        "ie": "Ireland",
        "il": "Israel",
        "in": "India",
        "is": "Iceland",
        "jp": "Japan",
        "kr": "South Korea",
        "kw": "Kuwait",
        "lb": "Lebanon",
        "lu": "Luxembourg",
        "ly": "Libya",
        "mt": "Malta",
        "mu": "Mauritius",
        "mw": "Malawi",
        "na": "Namibia",
        "nz": "New Zealand",
        "pa": "Panama",
        "pe": "Peru",
        "ph": "Philippines",
        "pk": "Pakistan",
        "pl": "Poland",
        "pr": "Puerto Rico",
        "pt": "Portugal",
        "py": "Paraguay",
        "qa": "Qatar",
        "ro": "Romania",
        "rs": "Serbia",
        "ru": "Russia",
        "sa": "Saudi Arabia",
        "se": "Sweden",
        "sg": "Singapore",
        "sk": "Slovakia",
        "sl": "Slovenia",
        "sm": "San Marino",
        "sn": "Senegal",
        "so": "Somalia",
        "sr": "Suriname",
        "sv": "El Salvador",
        "sy": "Syria",
        "sz": "Swaziland",
        "td": "Chad",
        "tg": "Togo",
        "th": "Thailand",
        "tj": "Tajikistan",
        "tn": "Tunisia",
        "tr": "Turkey",
        "tt": "Trinidad and Tobago",
        "tw": "Taiwan",
        "tz": "Tanzania",
        "ua": "Ukraine",
        "ug": "Uganda",
        "us": "United States",
        "uy": "Uruguay",
        "uz": "Uzbekistan",
        "va": "Vatican City",
        "ve": "Venezuela",
        "vn": "Vietnam",
        "ws": "Samoa",
        "ye": "Yemen",
        "yt": "Mayotte",
        "za": "South Africa",
        "zm": "Zambia",
        "zw": "Zimbabwe",
        "at": "Austria",
        "be": "Belgium",
        "cy": "Cyprus",
        "ee": "Estonia",
        "fi": "Finland",
        "gr": "Greece",
        "ie": "Ireland",
        "it": "Italy",
        "lv": "Latvia",
        "lt": "Lithuania",
        "lu": "Luxembourg",
        "mt": "Malta",
        "mc": "Monaco",
        "nl": "Netherlands",
        "pt": "Portugal",
        "sk": "Slovakia",
        "si": "Slovenia",
        "es": "Spain",
        "se": "Sweden",
        "gb": "United Kingdom",
        "au": "Australia",
        "nz": "New Zealand",
        "ca": "Canada",
        "us": "United States",
        "ar": "Argentina",
        "bo": "Bolivia",
        "br": "Brazil",
        "cl": "Chile",
        "co": "Colombia",
        "cr": "Costa Rica",
        "cu": "Cuba",
        "do": "Dominican Republic",
        "ec": "Ecuador",
        "sv": "El Salvador",
        "gq": "Equatorial Guinea",
        "gt": "Guatemala",
        "hn": "Honduras",
        "mx": "Mexico",
        "ni": "Nicaragua",
        "pa": "Panama",
        "py": "Paraguay",
        "pe": "Peru",
        "pr": "Puerto Rico",
        "uy": "Uruguay",
        "ve": "Venezuela",
        "dz": "Algeria",
        "ao": "Angola",
        "bj": "Benin",
        "bw": "Botswana",
        "bf": "Burkina Faso",
        "bi": "Burundi",
        "cm": "Cameroon",
        "cv": "Cape Verde",
        "cf": "Central African Republic",
        "td": "Chad",
        "km": "Comoros",
        "cg": "Congo",
        "cd": "Congo, The Democratic Republic of the",
        "dj": "Djibouti",
        "eg": "Egypt",
        "gq": "Equatorial Guinea",
        "er": "Eritrea",
        "et": "Ethiopia",
        "ga": "Gabon",
        "gm": "Gambia",
        "gh": "Ghana",
        "gn": "Guinea",
        "gw": "Guinea-Bissau",
        "ci": "Ivory Coast",
        "ke": "Kenya",
        "ls": "Lesotho",
        "lr": "Liberia",
        "ly": "Libya",
        "mg": "Madagascar",
        "mw": "Malawi",
        "ml": "Mali",
        "mr": "Mauritania",
        "mu": "Mauritius",
        "yt": "Mayotte",
        "ma": "Morocco",
        "mz": "Mozambique",
        "na": "Namibia",
        "ne": "Niger",
        "ng": "Nigeria",
        "re": "Réunion",
        "rw": "Rwanda",
        "sh": "Saint Helena, Ascension and Tristan da Cunha",
        "st": "São Tomé and Príncipe",
        "sn": "Senegal",
        "sc": "Seychelles",
        "sl": "Sierra Leone",
        "so": "Somalia",
        "za": "South Africa",
        "ss": "South Sudan",
        "sd": "Sudan",
        "sz": "Swaziland",
        "tz": "Tanzania",
        "tg": "Togo",
        "tn": "Tunisia",
        "ug": "Uganda",
        "eh": "Western Sahara",
        "zm": "Zambia",
        "zw": "Zimbabwe",
        "af": "Afghanistan",
        "am": "Armenia",
        "az": "Azerbaijan",
        "bh": "Bahrain",
        "bd": "Bangladesh",
        "bt": "Bhutan",
        "bn": "Brunei",
        "mm": "Burma",
        "kh": "Cambodia",
        "cn": "China",
        "cy": "Cyprus",
        "ge": "Georgia",
        "in": "India",
        "id": "Indonesia",
        "ir": "Iran",
        "iq": "Iraq",
        "il": "Israel",
        "jp": "Japan",
        "jo": "Jordan",
        "kz": "Kazakhstan",
        "kp": "North Korea",
        "kr": "South Korea",
        "kw": "Kuwait",
        "kg": "Kyrgyzstan",
        "la": "Laos",
        "lb": "Lebanon",
        "my": "Malaysia",
        "mv": "Maldives",
        "mn": "Mongolia",
        "np": "Nepal",
        "om": "Oman",
        "pk": "Pakistan",
        "ps": "Palestine",
        "ph": "Philippines",
        "qa": "Qatar",
        "sa": "Saudi Arabia",
        "sg": "Singapore",
        "lk": "Sri Lanka",
        "sy": "Syria",
        "tw": "Taiwan",
        "tj": "Tajikistan",
        "th": "Thailand",
        "tr": "Turkey",
        "tm": "Turkmenistan",
        "ae": "United Arab Emirates",
        "uz": "Uzbekistan",
        "vn": "Vietnam",
        "ye": "Yemen",
        "al": "Albania",
        "ad": "Andorra",
        "at": "Austria",
        "by": "Belarus",
        "be": "Belgium",
        "ba": "Bosnia and Herzegovina",
        "bg": "Bulgaria",
        "hr": "Croatia",
        "cy": "Cyprus",
        "cz": "Czech Republic",
        "dk": "Denmark",
        "ee": "Estonia",
        "fo": "Faroe Islands",
        "fi": "Finland",
        "fr": "France",
        "de": "Germany",
        "gi": "Gibraltar",
        "gr": "Greece",
        "hu": "Hungary",
        "is": "Iceland",
        "ie": "Ireland",
        "im": "Isle of Man",
        "it": "Italy",
        "rs": "Kosovo",
        "lv": "Latvia",
        "li": "Liechtenstein",
        "lt": "Lithuania",
        "lu": "Luxembourg",
        "mk": "Macedonia",
        "mt": "Malta",
        "md": "Moldova",
        "mc": "Monaco",
        "me": "Montenegro",
        "nl": "Netherlands",
        "no": "Norway",
        "pl": "Poland",
        "pt": "Portugal",
        "ro": "Romania",
        "sm": "San Marino",
        "rs": "Serbia",
        "sk": "Slovakia",
        "si": "Slovenia",
        "es": "Spain",
        "sj": "Svalbard and Jan Mayen",
        "se": "Sweden",
        "ch": "Switzerland",
        "ua": "Ukraine",
        "gb": "United Kingdom",
        "va": "Vatican City",
        "ag": "Antigua and Barbuda",
        "bs": "Bahamas",
        "bb": "Barbados",
        "bz": "Belize",
        "ca": "Canada",
        "cr": "Costa Rica",
        "cu": "Cuba",
        "dm": "Dominica",
        "do": "Dominican Republic",
        "sv": "El Salvador",
        "gd": "Grenada",
        "gt": "Guatemala",
        "ht": "Haiti",
        "hn": "Honduras",
        "jm": "Jamaica",
        "mx": "Mexico",
        "ni": "Nicaragua",
        "pa": "Panama",
        "kn": "Saint Kitts and Nevis",
        "lc": "Saint Lucia",
        "vc": "Saint Vincent and the Grenadines",
        "tt": "Trinidad and Tobago",
        "us": "United States",
        "ar": "Argentina",
        "bo": "Bolivia",
        "br": "Brazil",
        "cl": "Chile",
        "co": "Colombia",
        "ec": "Ecuador",
        "fk": "Falkland Islands",
        "gf": "French Guiana",
        "gy": "Guyana",
        "py": "Paraguay",
        "pe": "Peru",
        "sr": "Suriname",
        "uy": "Uruguay",
        "ve": "Venezuela",
        "af": "Afghanistan",
        "am": "Armenia",
        "az": "Azerbaijan",
        "bh": "Bahrain",
        "bd": "Bangladesh",
        "bt": "Bhutan",
        "bn": "Brunei",
        "mm": "Burma",
        "kh": "Cambodia",
        "cn": "China",
        "cy": "Cyprus",
        "ge": "Georgia",
        "in": "India",
        "id": "Indonesia",
        "ir": "Iran",
        "iq": "Iraq",
        "il": "Israel",
        "jp": "Japan",
        "jo": "Jordan",
        "kz": "Kazakhstan",
        "kp": "North Korea",
        "kr": "South Korea",
        "kw": "Kuwait",
        "kg": "Kyrgyzstan",
        "la": "Laos",
        "lb": "Lebanon",
        "my": "Malaysia",
        "mv": "Maldives",
        "mn": "Mongolia",
        "np": "Nepal",
        "om": "Oman",
        "pk": "Pakistan",
        "ps": "Palestine",
        "ph": "Philippines",
        "qa": "Qatar",
        "sa": "Saudi Arabia",
        "sg": "Singapore",
        "lk": "Sri Lanka",
        "sy": "Syria",
        "tw": "Taiwan",
        "tj": "Tajikistan",
        "th": "Thailand",
        "tr": "Turkey",
        "tm": "Turkmenistan",
        "ae": "United Arab Emirates",
        "uz": "Uzbekistan",
        "vn": "Vietnam",
        "ye": "Yemen",
        "al": "Albania",
        "ad": "Andorra",
        "at": "Austria",
        "by": "Belarus",
        "be": "Belgium",
        "ba": "Bosnia and Herzegovina",
        "bg": "Bulgaria",
        "hr": "Croatia",
        "cy": "Cyprus",
        "cz": "Czech Republic",
        "dk": "Denmark",
        "ee": "Estonia",
        "fo": "Faroe Islands",
        "fi": "Finland",
        "fr": "France",
        "de": "Germany",
        "gi": "Gibraltar",
        "gr": "Greece",
        "hu": "Hungary",
        "is": "Iceland",
        "ie": "Ireland",
        "im": "Isle of Man",
        "it": "Italy",
        "rs": "Kosovo",
        "lv": "Latvia",
        "li": "Liechtenstein",
        "lt": "Lithuania",
        "lu": "Luxembourg",
        "mk": "Macedonia",
        "mt": "Malta",
        "md": "Moldova",
        "mc": "Monaco",
        "me": "Montenegro",
        "nl": "Netherlands",
        "no": "Norway",
        "pl": "Poland",
        "pt": "Portugal",
        "sm": "San Marino",
        "rs": "Serbia",
        "sk": "Slovakia",
        "si": "Slovenia",
        "zw": "Zimbabwe"
    }
