class Nation:
    nation_mapping = {
        "zh": "China",
        "en": "English-speaking country",
        "ja": "Japan",
        "ko": "Korea",
        "ru": "Russia",
        "de": "Germany",
        "fr": "France",
        "es": "Spanish-speaking country",
        "it": "Italy",
        "pt": "Portuguese-speaking country",
        "ar": "Arabic-speaking country",
        "hi": "India",
        "th": "Thailand",
        "vi": "Vietnam",
        "nl": "Netherlands",
        "sv": "Sweden",
        "no": "Norway",
        "fi": "Finland",
        "da": "Denmark",
        "pl": "Poland",
        "tr": "Turkey",
        "he": "Israel",
        "uk": "Ukraine",
        "el": "Greece",
        "hu": "Hungary",
        "cs": "Czech Republic",
        "ro": "Romania",
        "bg": "Bulgaria",
        "sr": "Serbia",
        "hr": "Croatia",
        "sk": "Slovakia",
        "lt": "Lithuania",
        "lv": "Latvia",
        "et": "Estonia",
        "ms": "Malaysia",
        "id": "Indonesia",
        "tl": "Philippines",
        "fa": "Iran",
        "bn": "Bangladesh",
        "ur": "Pakistan",
        "am": "Ethiopia",
        "sw": "Swahili-speaking country",
        "my": "Myanmar",
        "ne": "Nepal",
        "si": "Sri Lanka",
        "mn": "Mongolia",
        "km": "Cambodia",
        "la": "Laos",
        "ps": "Palestine",
        "af": "Afghanistan",
        "kg": "Kyrgyzstan",
        "uz": "Uzbekistan",
        "tj": "Tajikistan",
        "az": "Azerbaijan",
        "ge": "Georgia",
        "md": "Moldova",
        "bh": "Bahrain",
        "qa": "Qatar",
        "om": "Oman",
        "ye": "Yemen",
        "dz": "Algeria",
        "ma": "Morocco",
        "tn": "Tunisia",
        "sn": "Senegal",
        "gh": "Ghana",
        "ng": "Nigeria",
        "za": "South Africa",
        "ci": "Ivory Coast",
        "cd": "Congo",
        "ao": "Angola",
        "ug": "Uganda",
        "mz": "Mozambique",
        "zm": "Zambia",
        "zw": "Zimbabwe",
        "bw": "Botswana",
        "ke": "Kenya"
    }
